[project]
name = "yolo-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.12.0.88",
    "streamlit>=1.47.1",
    "ultralytics>=8.3.174",
]
